### ISSUE TITLE
Request for the model trained on JHU and NWPU

### ISSUE THREAD

**Issue by jimmy-dq** [hustaia/Decoupled_Two-stage_Counting#1]
Hi，
Thanks for your great work. Could you please provide the models trained on JHU and NWPU?

**Comment by hustaia** [comment]
Pretrained model for JHU (Overall MAE: 73.7, MSE: 292.6)
BaiduYun link: https://pan.baidu.com/s/1M8FhtCFyHm-XZPMh6Gz0Rg
code: vb06
Pretrained model for NWPU (Overall MAE on val set: 84.8, MSE: 767.7)
BaiduYun link: https://pan.baidu.com/s/1ZEOR-w9LFG8PQCpowJdmNQ
code: 49z4

**Comment by jimmy-dq** [comment]
Many thanks for your help and your excellent work.
